spring:
  application:
    name: vendas-api
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    continue-on-error: 'true'
    password: ''
    initialize: 'true'
  jpa:
    show-sql: true
  h2:
    console:
      enabled: 'true'
      path: /h2-console